myProjectApp/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

views = Blueprint('views', __name__)


@views.route('/about')
def about():
    return render_template("about.html")


@views.route('/')
@login_required
def home():
    from .models import Tracker
    tracker = Tracker.query.all()
    return render_template("home.html", user=current_user, tracker=tracker)


@views.route('/view-profile', methods=['GET', 'POST'])
@login_required
def view_profile():
    return render_template("profile_page.html", user=current_user)


@views.route('/edit-profile-page', methods=['GET', 'POST'])
@login_required
def edit_profile_page():
    try:
        if request.method == 'POST':
            email = request.form.get('email')
            fullname = request.form.get('name')
            city = request.form.get('city')
            user_id = current_user.id
            current_user_email = current_user.email

            from .models import User
            user = User.query.filter_by(email=email).first()
            if user and current_user_email != email:
                flash('Email is already taken, try another email.', category='error')
            elif len(fullname) < 3:
                flash('Full name must be greater than 2 characters.', category='error')
            elif len(email) < 4:
                flash('Email must be greater than 3 characters.', category='error')
            else:
                from .models import User
                edit_user = User.query.get(user_id)

                from . import db

                edit_user.fullname = fullname
                edit_user.email = email
                edit_user.city = city

                db.session.commit()
                flash('Profile Updated Successfully.', category='success')
                return redirect(url_for('views.view_profile'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("edit_profile_page.html", user=current_user)


@views.route('/add-tracker-page', methods=['GET', 'POST'])
@login_required
def add_tracker_page():
    try:
        if request.method == 'POST':
            name = request.form.get('name')
            description = request.form.get('description')
            tracker_type = request.form.get('type')
            settings = request.form.get('settings')

            from .models import Tracker
            current_user_id = current_user.id
            tracker = Tracker.query.filter_by(name=name).first()
            if tracker and current_user_id == tracker.user_id:
                flash('The tracker "' + name + '" is already added by you.', category='error')
                return redirect(url_for('views.home'))
            else:
                from . import db
                new_tracker = Tracker(name=name, description=description, tracker_type=tracker_type, settings=settings,
                                      user_id=current_user_id)
                db.session.add(new_tracker)
                db.session.commit()
                flash('New Tracker Added.', category='success')
                return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("add_tracker_page.html", user=current_user)


@views.route('/delete-tracker/<int:record_id>', methods=['GET', 'POST'])
@login_required
def delete_tracker(record_id):
    try:
        from .models import Tracker
        Tracker_details = Tracker.query.get(record_id)
        Tracker_name = Tracker_details.name
        from . import db
        db.session.delete(Tracker_details)
        db.session.commit()
        flash(Tracker_name + ' Tracker Removed Successfully.', category='success')
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return redirect(url_for('views.home'))


@views.route('/edit-tracker/<int:record_id>', methods=['GET', 'POST'])
@login_required
def edit_tracker(record_id):
    from .models import Tracker
    this_tracker = Tracker.query.get(record_id)
    this_tracker_name = this_tracker.name
    try:
        if request.method == 'POST':
            name = request.form.get('name')
            description = request.form.get('description')
            tracker_type = request.form.get('type')
            settings = request.form.get('settings')

            current_user_id = current_user.id
            tracker = Tracker.query.filter_by(name=name).first()
            if tracker and tracker.user_id == current_user_id and this_tracker_name != name:
                flash('The tracker "' + name + '" is already added by you, Try a new name for your tracker.',
                      category='error')
            else:
                from . import db

                this_tracker.name = name
                this_tracker.description = description
                this_tracker.tracker_type = tracker_type
                this_tracker.settings = settings

                db.session.commit()
                flash('Tracker Updated Successfully.', category='success')
                return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')

    return render_template("edit_tracker_page.html", user=current_user, tracker=this_tracker)


@views.route('/add-log-page/<int:record_id>', methods=['GET', 'POST'])
@login_required
def add_log(record_id):
    from .models import Tracker, Log
    this_tracker = Tracker.query.get(record_id)
    import datetime
    now = datetime.datetime.now()
    try:
        if request.method == 'POST':
            when = request.form.get('date')
            value = request.form.get('value')
            notes = request.form.get('notes')
            from . import db
            new_log = Log(timestamp=when, value=value, notes=notes, tracker_id=record_id, user_id=current_user.id,
                          added_date_time=now)
            db.session.add(new_log)
            db.session.commit()
            flash('New Log Added For ' + this_tracker.name + ' Tracker', category='success')
            return redirect(url_for('views.home'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("add_log_page.html", user=current_user, tracker=this_tracker, now=now)


@views.route('/view-tracker-graph-logs/<int:record_id>', methods=['GET', 'POST'])
@login_required
def view_tracker(record_id):
    from .models import Tracker, Log
    import datetime
    now = datetime.datetime.now()
    selected_tracker = Tracker.query.get(record_id)
    logs = Log.query.all()
    try:
        import sqlite3
        con = sqlite3.connect('F:\MAD1\myProjectApp\data.sqlite')
        print("Database opened successfully")
        c = con.cursor()
        c.execute('SELECT timestamp, value FROM Log WHERE user_id={} AND tracker_id={}'.format(current_user.id,
                                                                                               selected_tracker.id))
        data = c.fetchall()

        dates = []
        values = []
        import matplotlib.pyplot as plt
        from matplotlib import style
        style.use('fivethirtyeight')
        from dateutil import parser

        for row in data:
            dates.append(parser.parse(row[0]))
            values.append(row[1])

        fig = plt.figure(figsize=(18, 8))
        plt.plot_date(dates, values, '-')
        plt.xlabel('Date and Time')
        plt.ylabel('Values')
        plt.tight_layout()
        plt.savefig('F:/MAD1/myProjectApp/static/Images/graph.png')
        # plt.show()

        gon = sqlite3.connect('F:/MAD1/myProjectApp/data.sqlite')
        g = gon.cursor()
        added_date_time = g.execute('SELECT added_date_time FROM Log WHERE '
                                    'id=(SELECT max(id) FROM Log WHERE tracker_id={})'.format(record_id))

        added_date_time = added_date_time.fetchone()
        added_date_time = ''.join(added_date_time)
        print(added_date_time)
        from datetime import datetime
        last_updated = now - parser.parse(added_date_time)
        last_updated_str = str(last_updated)
        hour = last_updated_str[:1]
        min1 = last_updated_str[2]
        min2 = last_updated_str[3]
        minute = min1 + min2
        sec1 = last_updated_str[5]
        sec2 = last_updated_str[6]
        second = sec1 + sec2
        return render_template("view_tracker_logs_and_graph.html", user=current_user, tracker=selected_tracker,
                               logs=logs, hour=hour, min=minute, sec=second)
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
        return render_template("view_tracker_logs_and_graph.html", user=current_user, tracker=selected_tracker,
                               logs=logs)


@views.route('/delete-log/<int:record_id>', methods=['GET', 'POST'])
@login_required
def delete_log(record_id):
    from .models import Log
    Log_details = Log.query.get(record_id)
    tracker_id = Log_details.tracker_id
    try:
        from . import db
        db.session.delete(Log_details)
        db.session.commit()
        flash('Log Removed Successfully.', category='success')
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return redirect(url_for('views.view_tracker', record_id=tracker_id))


@views.route('/edit-log/<int:record_id>', methods=['GET', 'POST'])
@login_required
def edit_log(record_id):
    from .models import Log, Tracker
    from . import db

myProjectApp/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
    <style>
        body{
            background-color: antiquewhite;
        }
        .about_us{
            text-align: center;
            font-size: 20px;
            padding: 10px;
            margin: auto;

        }
    </style>
</head>
<body>
    <h1 style="text-align: center">Quantified Self App</h1>
    <div class="about_us">

    <p>Used for self tracking - tracking habits, activities, other life parameters etc.
        The quantified self refers both to the cultural phenomenon of self-tracking with technology and
        to a community of users and makers of self-tracking tools who share an interest in "self-knowledge through
        numbers". Quantified self practices overlap with the practice of lifelong and other trends that
        incorporate technology and data acquisition into daily life, often with the goal of improving physical, mental,
        and emotional performance. The widespread adoption in recent years of wearable fitness and sleep trackers such
        as the Fitbit or the Apple Watch, combined with the increased presence of Internet of things in healthcare
        and in exercise equipment, have made self-tracking accessible to a large segment of the population.
        Other terms for using self-tracking data to improve daily functioning are auto-analytics, body hacking,
        self-quantifying, self-surveillance, surveillance (recording of personal activity), and personal informatics.</p>
    <br>
    <p>A major application of quantified self has been in health and wellness improvement. Many devices and services
        help with tracking physical activity, caloric intake, sleep quality, posture, and other factors involved in
        personal well-being. Corporate wellness programs, for example, will often encourage some form of tracking.
        Genetic testing and other services have also become popular.</p>
    <br>
    <p>Quantified self is also being used to improve personal or professional productivity, with tools and services being
    used to help people keep track of what they do during the workday, where they spend their time, and whom they
    interact with.</p>
    </div>
    <span>Source : <a href="https://en.wikipedia.org/wiki/Quantified_self">Wikipedia</a> </span>
</body>
</html>

myProjectApp/templates/add_log_page.html
{% extends 'base.html' %}
{% block title %}Add Log{% endblock %}
{% block content %}
        <h1 align="left" class="card-header text-white" style="background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">Hello, {{ user.fullname }}</h1>

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">

        <h2 style="padding-left: 568px">Log {{tracker.name}}</h2>

        <div align="center">

            <br>

             <label for="date">When: </label>
        <input
            type="datetime-local"
            class="form-control"
            id="date"
            name="date"
            style="width: 300px; border-radius: 15px; text-align: center"
            value="{{now}}"
            required
        />
        <label for="value">Value: </label>
{% if tracker.tracker_type=='Numerical'  %}

        <input
            type="number"
            class="form-control"
            id="value"
            name="value"
            placeholder="Enter Number"
            maxlength="30"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        />
{% elif tracker.tracker_type=='Fahrenheit' %}
        <input
            type="number"
            class="form-control"
            id="value"
            name="value"
            placeholder="Enter Fahrenheit"
            maxlength="30"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        />
{% elif tracker.tracker_type=='Multiple Choice' %}
                        <select style="width: 300px;text-align: center;border-radius: 15px;" id="value"  class="form-control"  name="value" required>
                            <option value="Happy">Happy</option>
                            <option value="Sad">Sad</option>
                            <option value="Angry">Angry</option>
                            <option value="Depressed">Depressed</option>
                            <option value="Anxious">Anxious</option>

                            </select>

{% elif tracker.tracker_type=='Boolean' %}
            <br>
            <input type="radio" id="value" name="value" value="True" checked>
             <label for="value">True</label><br>
             <input type="radio" id="value" name="value" value="False">
             <label for="value">False</label><br>

{% endif %}

            <label for="notes">Notes: </label>
        <textarea
            class="form-control"
            id="notes"
            name="notes"
            placeholder="Enter log notes"
            maxlength="200"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        ></textarea>


            <br>
            <button type="submit" class="btn" style="border-radius: 12px;background: -webkit-linear-gradient(top, #FF5E0E, #FF9944);"><b>✩ Add Log</b></button>

        </div>


    </div>
</form>

{% endblock %}

myProjectApp/templates/add_tracker_page.html
{% extends 'base.html' %}
{% block title %}Add Tracker{% endblock %}
{% block content %}
        <h1 align="left" class="card-header text-white" style="background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">Hello, {{ user.fullname }}</h1>

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">

        <h2 style="padding-left: 580px">Add Tracker</h2>

        <div align="center">


            <br>

             <label for="name">Name</label>
        <input
            type="text"
            class="form-control"
            id="name"
            name="name"
            placeholder="Enter tracker name"
            maxlength="30"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        />
            <label for="description">Description</label>
        <textarea
            class="form-control"
            id="description"
            name="description"
            placeholder="Enter tracker description"
            maxlength="200"
            style="width: 300px; border-radius: 15px; text-align: center"
            required
        ></textarea>


            <label style="padding-top: 10px" for="type">Tracker Type</label>
                        <select style="width: 300px;border-radius: 15px; text-align: center" id="type"  class="form-control"  name="type" required>
                            <option value="Numerical">Numerical</option>
                            <option value="Multiple Choice">Multiple Choice</option>
                            <option value="Fahrenheit">Fahrenheit</option>
                            <option value="Boolean">Boolean</option>


                        </select>

          <label for="settings">Settings <small>(Optional)</small></label>
        <input
            type="text"
            class="form-control"
            id="settings"
            name="settings"
            placeholder="Enter tracker settings"
            maxlength="80"
            style="width: 300px; border-radius: 15px; text-align: center"
        />

            <br>
            <button type="submit" class="btn" style="border-radius: 12px;background: -webkit-linear-gradient(top, #FF5E0E, #FF9944);"><b>✩ Add Tracker</b></button>

        </div>


    </div>
</form>

{% endblock %}

myProjectApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="../static/index.css" />
</head>
<body>
<!--Nav bar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">

            {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="profile" href="/view-profile">View Profile</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                <a class="nav-item nav-link" id="about" href="/about">About</a>
            {% endif %}

        </div>
      </div>
    </nav>
<!--End of Nav Bar-->
    <div  >


    </div>



<!-- Error and Success Message-->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}

                {% for category, message in messages %}

                    {% if category == 'error' %}
                        <div align="center">
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                              {{ message }}
                              <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                        </div>
                    {% else %}
                        <div align="center">
                            <div class="alert alert-success alter-dismissable fade show" role="alert">
                              {{ message }}
                              <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                        </div>
                    {% endif %}

                {% endfor %}

        {% endif %}
    {% endwith %}
<!-- End of Error and Success Message-->


<!--Content of each page-->
{% block content %}


{% endblock %}
<!--End of Content of each page-->


<br><br><br>
<!--Footer-->
<div class="footer" >
    <h5>Quantified Self App used for tracking your habits</h5>
    <p class="text-secondary">© 2022 All rights reserved </p>

</div>
<!--end of Footer-->

<!--scripts-->
<script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

 <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
<!--end of scripts-->

</body>
</html>

myProjectApp/templates/edit_log_page.html
{% extends 'base.html' %}
{% block title %}Edit Log{% endblock %}

{% block content %}
        <h1 align="left" class="card-header text-white" style="background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">Hello, {{ user.fullname }}</h1>

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">

        <h2 style="padding-left: 538px">Edit Log {{tracker.name}}</h2>

        <div align="center">

            <br>

            <label for="date">When: </label>
        <input
            type="datetime-local"
            class="form-control"
            id="date"
            name="date"
            style="width: 300px; border-radius: 15px; text-align: center"
            value="{{log.timestamp}}"
        />
        <label for="value">Value: </label>
{% if tracker.tracker_type=='Numerical'  %}

        <input
            type="number"
            class="form-control"
            id="value"
            name="value"
            placeholder="Enter Number"
            maxlength="30"
            style="width: 300px; border-radius: 15px; text-align: center"
            value="{{log.value}}"
        />
{% elif tracker.tracker_type=='Fahrenheit' %}
        <input
            type="number"
            class="form-control"
            id="value"
            name="value"
            placeholder="Enter Fahrenheit"
            maxlength="30"
            style="width: 300px; border-radius: 15px; text-align: center"
            value="{{log.value}}"
        />
{% elif tracker.tracker_type=='Multiple Choice' %}
                        <select style="width: 300px;text-align: center;border-radius: 15px;" id="value"  class="form-control"  name="value" required>
                            <option value="{{log.value}}">{{log.value}}</option>
                            <option value="Happy">Happy</option>
                            <option value="Sad">Sad</option>
                            <option value="Angry">Angry</option>
                            <option value="Depressed">Depressed</option>
                            <option value="Anxious">Anxious</option>

                            </select>


{% elif tracker.tracker_type=='Boolean' %}
            <br>
            {% if log.value=='True' %}
            <input type="radio" id="value" name="value" value="{{log.value}}" checked>
            <label for="value">{{log.value}}</label><br>
            <input type="radio" id="value" name="value" value="False">
            <label for="value">False</label><br>
            {% else %}
            <input type="radio" id="value" name="value" value="True">
            <label for="value">True</label><br>
            <input type="radio" id="value" name="value" value="{{log.value}}" checked>
            <label for="value">{{log.value}}</label><br>
            {% endif %}

{% endif %}

            <label for="notes">Notes: </label>
        <textarea
            class="form-control"
            id="notes"
            name="notes"
            placeholder="Enter log notes"
            maxlength="200"
            style="width: 300px; border-radius: 15px; text-align: center"

        >{{log.notes}}</textarea>


            <br>
            <button type="submit" class="btn" style="border-radius: 12px;background: -webkit-linear-gradient(top, #FF5E0E, #FF9944);"><b>✩ Update Log</b></button>

        </div>


    </div>
</form>

{% endblock %}

myProjectApp/templates/home.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}
        <h1 align="left" class="card-header text-white" style="background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">Welcome {{ user.fullname }}, How you're doing !</h1>

<br>
<div class="container emp-profile shadow-lg" style="padding-top: 30px">

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Tracker</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
{% for tracker in tracker %}
    {% if tracker.user_id==user.id  %}
    <tr>
        {% set tracker_id=tracker.id %}
      <td><a href="{{ url_for('views.view_tracker', record_id = tracker_id) }}">{{tracker.name}}</a></td>
      <td>{{tracker.description}}</td>
      <td><a href="{{ url_for('views.add_log', record_id = tracker_id) }}" class="btn" style="border-radius: 15px; font-size: 20px">✚</a></td>
      <td>

          <div class="dropdown">
  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border-radius: 15px;background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">
    <b>Actions</b>
  </button>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{{ url_for('views.edit_tracker', record_id = tracker_id) }}">Edit Tracker</a>
    <a class="dropdown-item" href="{{ url_for('views.delete_tracker', record_id = tracker_id) }}">Remove Tracker</a>
  </div>
</div>

      </td>
    </tr>
{% endif %}
    {% endfor %}

  </tbody>
</table>

        <div align="center">
            <a href="/add-tracker-page" class="btn" style="border-radius: 15px;background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);"><b>✩ Add Tracker</b></a>
                    </div>
</div>
{% endblock %}

myProjectApp/templates/view_tracker_logs_and_graph.html
{% extends 'base.html' %}
{% block title %}View Tracker Logs{% endblock %}
{% block content %}
        <h1 align="left" class="card-header text-white" style="background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">Hello, {{ user.fullname }}</h1>

<div class="container emp-profile shadow-lg" style="padding-top: 30px">
            <form method="post">
                <div class="row">

                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h3>
                                      <b>{{ tracker.name }} - Tracker </b>
                                    </h3>
                                    <h4>&nbsp<small style="font-size: 12px">last updated : {{hour}} hours {{min}} minutes {{sec}} seconds ago</small></h4>

                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Graph</a>
                                </li>

                            </ul>

                        </div>
                    </div>

                </div>
                <div class="row">

                    <div class="col-md-8" style="padding-top: 5px; padding-left: 32px">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">


                            <img src="{{url_for('static',filename='Images/graph.png')}}" alt="" style="width: 900px;height: 350px">
<br><br>
                            </div>

                        </div>
                    </div>
                </div>

                <ul class="nav nav-tabs" id="myTab2" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab2" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Logs</a>
                                </li>

                            </ul>
<!--                -->

                <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">On</th>
        <th scope="col">Value</th>
      <th scope="col">Notes</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
{% for log in logs %}
    {% if log.user_id==user.id and log.tracker_id==tracker.id %}
    <tr>
        {% set log_id=log.id %}
      <td>{{log.timestamp}}</td>
      <td>{{log.value}}</td>
      <td>{{log.notes}}</td>
      <td>

          <div class="dropdown">
  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border-radius: 15px;background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);">
    <b>Actions</b>
  </button>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{{ url_for('views.edit_log', record_id = log_id) }}">Edit Log</a>
    <a class="dropdown-item" href="{{ url_for('views.delete_log', record_id = log_id) }}">Remove Log</a>
  </div>
</div>

      </td>
    </tr>
{% endif %}
    {% endfor %}

  </tbody>
</table>

<!--                -->
{% set tracker_id=tracker.id %}
<div align="center">
            <a href="{{ url_for('views.add_log', record_id = tracker_id) }}" class="btn" style="border-radius: 15px;background: -webkit-linear-gradient(bottom, #FF5E0E, #FF9944);"><b>✩ Add New Log</b></a>
                    </div>
            </form>
        </div>
{% endblock %}